import { createSlice } from '@reduxjs/toolkit';

const initialProducts = [
    {
        id: 'prod-101',
        name: 'Lorem Apex Headphones',
        subtitle: 'Wireless Active Noise Cancelling Audio',
        price: 249.99,
        originalPrice: 299.99,
        category: 'Electronics',
        rating: 4.8,
        reviewsCount: 124,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo. Premium acoustic drivers deliver ultra-rich sound clarity.',
        specs: ['Bluetooth 5.3', '35-Hour Battery Life', 'Active Noise Cancellation', 'USB-C Fast Charging'],
        isFeatured: true,
        isNew: true,
        stock: 18,
    },
    {
        id: 'prod-102',
        name: 'Ipsum Minimalist Chronograph',
        subtitle: 'Brushed Stainless Steel Timepiece',
        price: 189.00,
        originalPrice: 220.00,
        category: 'Accessories',
        rating: 4.9,
        reviewsCount: 89,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
        description: 'Lorem ipsum dolor sit amet, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sapphire crystal glass with genuine leather strap.',
        specs: ['Japanese Quartz Movement', '5 ATM Water Resistant', '40mm Stainless Case', 'Italian Leather Strap'],
        isFeatured: true,
        isNew: false,
        stock: 12,
    },
    {
        id: 'prod-103',
        name: 'Dolor Smart Ergonomics Chair',
        subtitle: 'Lumbar Support Executive Desk Seat',
        price: 450.00,
        originalPrice: 520.00,
        category: 'Furniture',
        rating: 4.7,
        reviewsCount: 65,
        image: 'https://images.unsplash.com/photo-1580481072645-022f9a6d85d5?auto=format&fit=crop&w=600&q=80',
        description: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Engineered for all-day comfort and posture support.',
        specs: ['Dynamic Lumbar Support', 'Breathable Mesh Back', '4D Adjustable Armrests', 'Aluminum Base'],
        isFeatured: true,
        isNew: true,
        stock: 8,
    },
    {
        id: 'prod-104',
        name: 'Sit Amet Mechanical Keyboard',
        subtitle: 'Hot-swappable RGB Mechanical Keyboard',
        price: 135.50,
        originalPrice: 160.00,
        category: 'Electronics',
        rating: 4.9,
        reviewsCount: 210,
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
        description: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Pre-lubed linear switches with gasket mount.',
        specs: ['Gasket Mount Design', 'Tri-mode Wireless', 'PBT Double-shot Keycaps', 'Custom RGB Lighting'],
        isFeatured: false,
        isNew: true,
        stock: 25,
    },
    {
        id: 'prod-105',
        name: 'Consectetur Canvas Travel Bag',
        subtitle: 'Water-Resistant Weekender Duffel',
        price: 98.00,
        originalPrice: 120.00,
        category: 'Fashion',
        rating: 4.6,
        reviewsCount: 78,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Spacious shoe compartment included.',
        specs: ['Heavy-duty 16oz Canvas', 'Dedicated Laptop Sleeve', 'YKK Zippers', 'Removable Shoulder Strap'],
        isFeatured: false,
        isNew: false,
        stock: 30,
    },
    {
        id: 'prod-106',
        name: 'Adipiscing Ceramic Coffee Dripper',
        subtitle: 'Artisan Porcelain Pour-Over Set',
        price: 45.00,
        originalPrice: 55.00,
        category: 'Home & Kitchen',
        rating: 4.9,
        reviewsCount: 142,
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Handcrafted ceramic pour-over cone.',
        specs: ['Matte Glaze Finish', '600ml Heatproof Server', 'Spiral Rib Design', 'Includes 50 Filters'],
        isFeatured: true,
        isNew: false,
        stock: 45,
    },
    {
        id: 'prod-107',
        name: 'Elit Ultra Portable Projector',
        subtitle: '4K Supported Smart Mini Projector',
        price: 320.00,
        originalPrice: 380.00,
        category: 'Electronics',
        rating: 4.5,
        reviewsCount: 53,
        image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80',
        description: 'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur. Built-in Android OS with streaming apps.',
        specs: ['800 ANSI Lumens', 'Auto Keystone Correction', 'Harmon Kardon Audio', 'Compact Aluminum Body'],
        isFeatured: false,
        isNew: true,
        stock: 14,
    },
    {
        id: 'prod-108',
        name: 'Tempor Merino Wool Sweater',
        subtitle: '100% Organic Extra Fine Knitwear',
        price: 110.00,
        originalPrice: 140.00,
        category: 'Fashion',
        rating: 4.8,
        reviewsCount: 96,
        image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=600&q=80',
        description: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Breathable, temperature-regulating natural Merino wool.',
        specs: ['100% Merino Wool', 'Ribbed Cuffs & Hem', 'Regular Fit', 'Dry Clean Recommended'],
        isFeatured: false,
        isNew: false,
        stock: 20,
    }
];

const productsSlice = createSlice({
    name: 'products',
    initialState: {
        items: initialProducts,
        searchQuery: '',
        selectedCategory: 'All',
        sortBy: 'featured',
        selectedProduct: null,
    },
    reducers: {
        setSearchQuery: (state, action) => {
            state.searchQuery = action.payload;
        },
        setSelectedCategory: (state, action) => {
            state.selectedCategory = action.payload;
        },
        setSortBy: (state, action) => {
            state.sortBy = action.payload;
        },
        setSelectedProduct: (state, action) => {
            state.selectedProduct = action.payload;
        },
    },
});

export const { setSearchQuery, setSelectedCategory, setSortBy, setSelectedProduct } = productsSlice.actions;
export default productsSlice.reducer;
